name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build & test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[bus,test]"
          pip install build

      - name: Unit tests
        run: pytest -q

      - name: Schema sanity (optional)
        run: |
          python tools/validate.py --schema schema/ampy-config.schema.json examples/dev.yaml

  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go binaries
        run: |
          cd go/ampyconfig
          make

      - name: Test Go binaries
        run: |
          cd go/ampyconfig
          # Test that binaries can show help (don't run listener as it connects to NATS)
          ./bin/ampyconfig-ops -help
          ./bin/ampyconfig-agent -help
          # Test listener binary exists and is executable
          test -x ./bin/ampyconfig-listener

      - name: Verify Go module
        run: |
          cd go/ampyconfig
          go mod tidy
          go mod verify
