name: release
on:
  push:
    tags:
      - "v*.*.*"  # e.g., v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Python wheel/sdist
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Build Go binaries
        run: |
          cd go/ampyconfig
          make

      - name: Create release assets
        run: |
          mkdir -p release-assets
          cp dist/* release-assets/
          cd go/ampyconfig
          tar -czf ../../release-assets/ampyconfig-binaries-linux-amd64.tar.gz bin/
          cd bin
          for binary in ampyconfig-*; do
            cp "$binary" "../../../release-assets/"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-assets/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
